version: '3'
services:
  rtmp:
    container_name: rtmp_server
    build: .
    ports:
      - "1935:1935"
  scylla:
    image: scylladb/scylla
    command:
      - --smp=1
      - --listen-address=0.0.0.0
      - --broadcast-rpc-address=127.0.0.1
    ports:
      - "127.0.0.1:9042:9042"
    restart: unless-stopped