version: '3'
services:
  rtmp:
    container_name: rtmp_server
    build: .
    ports:
      - "1935:1935"
  chat:
    container_name: db
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=api_dev
